spring:
  application:
    name: senawiki
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

app:
  s3:
    bucket: senawiki-assets
    region: ap-northeast-2
    prefix: community
  assets:
    bucket: senawiki-assets
    region: ap-northeast-2
  hero-type-seed:
    enabled: false
  ses:
    region: ap-northeast-2
  jwt:
    access-token-validity-seconds: 900
    refresh-token-validity-seconds: 604800
server:
  address: 0.0.0.0
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
